spring:
  application:
    name: api_android
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/cham-cong-db

jwt:
  secret: QmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6
server:
  error:
    include-message: always